# Generated by Django 4.1.7 on 2023-06-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_habitacion_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cama',
            options={'verbose_name': 'Cama', 'verbose_name_plural': 'Camas Habitacion'},
        ),
        migrations.AlterModelOptions(
            name='detallereserva',
            options={'verbose_name_plural': 'Detalles Reserva'},
        ),
        migrations.AlterModelOptions(
            name='estadohabitacion',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados Habitacion'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos Habitacion'},
        ),
        migrations.AlterModelOptions(
            name='userextrainfo',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Info Extra Usuarios'},
        ),
    ]
