# Generated by Django 4.1.7 on 2023-06-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0003_alter_cama_options_alter_detallereserva_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos Cama',
            },
        ),
        migrations.RemoveField(
            model_name='cama',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cama',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cama',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cama',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.tipocama'),
        ),
    ]
